name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: debian:bullseye
    steps:
    - name: apt update
      run: apt update
    - name: build essential
      run: apt -y install build-essential
    - name: install gdal
      run: apt -y install gdal-bin gdal-data libgdal-dev

    - name: checkout code
      uses: actions/checkout@v3
      
    - name: checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
